feat: added submodules support and rewrote shebang

diff --git a/bin/git-commit b/bin/git-commit
--- a/bin/git-commit
+++ b/bin/git-commit
@@ -30,11 +30,14 @@ function synopsis() {
 
   cat << EOF
 \`\`\`bash
-$(basename "$0") [--edit|-e] [Optional Commit Message]
+$(basename "$0") [Options] [Optional Commit Message]
 \`\`\`
-* if the commit message is not given, it will be generated with the files in the commit.
-* \`--edit\` or \`-e\`          : edit the message in the editor
-* \`--no-recurse\` or \`-nr\`   : don't commit in the submodule
+  * Args:
+    * if the commit message is not given, it will be generated with the files in the commit.
+
+  * Options:
+    * \`--edit\` or \`-e\`          : edit the message in the editor
+    * \`--no-recurse\` or \`-nr\`   : don't recurse and commit in the submodules
 EOF
 
 }
@@ -80,8 +83,8 @@ if [ $RECURSE == true ] && [ ! -f .git ]; then
 
   # script dir is mandatory because we may call the next version
   # and git-commit in the PATH env var is generally the actual version
-  if ! git submodule foreach "$SCRIPT_DIR/git-commit ${ORIGINAL_ARGS[*]}"; then
-    echo::err "Error when committing to a submodule"
+  if ! git submodule foreach "$SCRIPT_DIR/$(basename "$0") ${ORIGINAL_ARGS[*]}"; then
+    echo::err "Error when executing $(basename "$0") to a submodule"
     exit 1
   fi
 
diff --git a/bin/git-feature-log b/bin/git-feature-log
--- a/bin/git-feature-log
+++ b/bin/git-feature-log
@@ -1,12 +1,12 @@
-#!/bin/bash
-# Delete a feature branch
-
+#!/usr/bin/env bash
+# List the commit until the branching from the default branch (ie main)
 
 set -Eeuo pipefail
 
+SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)"
+
 # Bash lib library path detection
 if [ "${BASHLIB_PATH:-}" == "" ]; then
-  SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)"
   # This is also a valid path for brew
   BASHLIB_PATH="$SCRIPT_DIR/../lib"
 fi
@@ -27,22 +27,53 @@ function synopsis(){
   cat <<EOF
 Shows the logs of commit in the feature branch (until the common ancestor with the default branch)
 \`\`\`bash
-$(basename "$0")
+$(basename "$0") [options]
 \`\`\`
+
+  Options:
+    * \`-nr\` or \`--no-recurse\` to not recurse in submodule
 EOF
 
 }
 
-# Doc Synopsis
-if [ "${1:-}" = "synopsis" ]; then
-  synopsis
-  exit 0
+RECURSE=true
+ORIGINAL_ARGS=("$@")
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -h | --help | help)
+      # Help
+      doc::help synopsis
+      exit 0
+      ;;
+    synopsis)
+      # Doc Synopsis
+      synopsis
+      exit 0
+      ;;
+    -nr | --no-recurse)
+      RECURSE=false
+      ;;
+  esac
+  shift
+done
+
+# First submodules
+# If not in a submodule (in a submodule .git is a file)
+# Otherwise the commit is only for the submodule
+if [ $RECURSE == true ] && [ ! -f .git ]; then
+
+  # script dir is mandatory because we may call the next version
+  # and git-commit in the PATH env var is generally the actual version
+  if ! git submodule foreach "$SCRIPT_DIR/$(basename "$0") ${ORIGINAL_ARGS[*]}"; then
+    echo::err "Error when executing $(basename "$0") to a submodule"
+    exit 1
+  fi
+
 fi
 
-# Help
-if [[ "${1:-}" =~ -h|--help|help ]]; then
-  doc::help synopsis
-  exit 0
+# Status of the actual repo
+if [ ! -f .git ]; then
+  echo "Entering main repo"
 fi
 
 
@@ -70,3 +101,8 @@ pretty_git_logs() {
 }
 pretty_git_logs "$DEFAULT_BRANCH..$BRANCH_NAME"
 echo::success "Done"
+
+if [ $RECURSE == true ]; then
+  # Spacing
+  echo ""
+fi
diff --git a/bin/git-feature-squash b/bin/git-feature-squash
--- a/bin/git-feature-squash
+++ b/bin/git-feature-squash
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # for doc, see markdown file
 
 set -Eeuo pipefail
@@ -32,16 +32,50 @@ EOF
 
 }
 
-# Doc Synopsis
-if [ "${1:-}" = "synopsis" ]; then
-  synopsis
-  exit 0
+RECURSE=false
+COMMIT_MESSAGE="feat: squash feature branch $BRANCH_NAME"
+ORIGINAL_ARGS=("$@")
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -h | --help | help)
+      # Help
+      doc::help synopsis
+      exit 0
+      ;;
+    synopsis)
+      # Doc Synopsis
+      synopsis
+      exit 0
+      ;;
+    -r | --recurse)
+      RECURSE=true
+      ;;
+    *)
+      COMMIT_MESSAGE=${1}
+      shift
+      break
+      ;;
+  esac
+  shift
+done
+
+# First submodules
+# If not in a submodule (in a submodule .git is a file)
+# Otherwise the commit is only for the submodule
+if [ $RECURSE == true ] && [ ! -f .git ]; then
+
+  # script dir is mandatory because we may call the next version
+  # and git-commit in the PATH env var is generally the actual version
+  if ! git submodule foreach "$SCRIPT_DIR/git-feature-squash ${ORIGINAL_ARGS[*]}"; then
+    echo::err "Error when squashing to a submodule"
+    exit 1
+  fi
+
 fi
 
-# Help
-if [[ "${1:-}" =~ -h|--help|help ]]; then
-  doc::help synopsis
-  exit 0
+# Status of the actual repo
+if [ ! -f .git ]; then
+  echo "Entering main repo"
 fi
 
 BRANCH_NAME=$(git::get_current_branch)
@@ -60,7 +94,6 @@ if git::is_dirty_index; then
 fi
 
 # Message before the reset
-COMMIT_MESSAGE=${1:-"feat: squash feature branch $BRANCH_NAME"}
 echo::info "Commit"
 BODY=$(git log --pretty=format:%s%n%b "$DEFAULT_BRANCH".."$BRANCH_NAME")
 SCISSOR_LINE="# ------------------------ >8 ------------------------"
diff --git a/bin/git-log b/bin/git-log
--- a/bin/git-log
+++ b/bin/git-log
@@ -1,11 +1,12 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # A improved version of `last = log -1 HEAD`
 
 set -Eeuo pipefail
 
+SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)"
+
 # Bash lib library path detection
 if [ "${BASHLIB_PATH:-}" == "" ]; then
-  SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)"
   # This is also a valid path for brew
   BASHLIB_PATH="$SCRIPT_DIR/../lib"
 fi
@@ -23,22 +24,52 @@ function synopsis() {
 
   cat << EOF
 \`\`\`bash
-$(basename "$0")
+$(basename "$0") [Options]
 \`\`\`
+
+  * \`-nr\` or \`--no-recurse\` to not recurse in submodule
 EOF
 
 }
 
-# Doc Synopsis
-if [ "${1:-}" = "synopsis" ]; then
-  synopsis
-  exit 0
+RECURSE=true
+ORIGINAL_ARGS=("$@")
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -h | --help | help)
+      # Help
+      doc::help synopsis
+      exit 0
+      ;;
+    synopsis)
+      # Doc Synopsis
+      synopsis
+      exit 0
+      ;;
+    -nr | --no-recurse)
+      RECURSE=false
+      ;;
+  esac
+  shift
+done
+
+# First submodules
+# If not in a submodule (in a submodule .git is a file)
+# Otherwise the commit is only for the submodule
+if [ $RECURSE == true ] && [ ! -f .git ]; then
+
+  # script dir is mandatory because we may call the next version
+  # and git-commit in the PATH env var is generally the actual version
+  if ! git submodule foreach "$SCRIPT_DIR/git-log ${ORIGINAL_ARGS[*]}"; then
+    echo::err "Error when executing git-log to a submodule"
+    exit 1
+  fi
+
 fi
 
-# Help
-if [[ "${1:-}" =~ -h|--help|help ]]; then
-  doc::help synopsis
-  exit 0
+# Status of the actual repo
+if [ ! -f .git ]; then
+  echo "Entering main repo"
 fi
 
 # https://git-scm.com/docs/git-config#Documentation/git-config.txt-color
@@ -70,3 +101,8 @@ FILES="$(colored_header 'Files'):"
 git show --name-status \
   --pretty=format:"${COMMIT_HASH}%n${AUTHOR}%n${AUTHOR_DATE}%n${COMMITTER}%n${COMMITTER_DATE}%n${BRANCH}%n${SUBJECT}%n${BODY}%n${FILES}" \
   HEAD
+
+if [ $RECURSE == true ]; then
+  # Spacing
+  echo ""
+fi
